name: Taskly Git Apk Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Install EAS CLI
        run: yarn global add eas-cli

      - name: Authenticate with Expo (Using EXPO_TOKEN)
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: echo "Expo authentication token set."

      - name: Initialize EAS (if needed)
        run: eas init || echo "EAS already initialized"

      - name: Build APK Locally
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas build --profile production --platform android --local

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Expo-APK
          path: ./build/**/*.apk  # Adjust path if needed
